# Disabled - Using Dockerfile instead
# [phases.setup]
# nixPkgs = []

# [phases.install]
# cmds = ["pip install -r requirements.txt"]

# [phases.build]
# cmds = ["echo 'Build complete'"]

# [start]
# cmd = "python app.py"
