[build]
# Force Railway to use Dockerfile instead of nixpacks
builder = "dockerfile"

[deploy]
startCommand = "python -u app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
